language: objective-c  # force osx for now.

os:
  - osx
#   # - linux

before_install:
  - brew update
  - brew tap optimizers/cutest
  - brew install cutest
  - brew brew install mastsif
  - pip install -q numpy

install:
  - python setup.py install



